---
output:
  pdf_document: default
  html_document: default
---
```{r}
#Jaini Shah
#QBS 103 Final Project
#Summer 2024

#Submission #1
```

```{r}
library(dplyr)
library(tidyr)
# set the working directory to where my csv file is located
getwd()
setwd("/Users/jainishah/Desktop/final_project_data")

#reading gene expression data and metadata files 
gene_expression <- read.csv("genes.csv")
metadata <- read.csv("metadata.csv")

head(gene_expression)
head(metadata)

# checking structure of gene expression data and metadata data 
#str(gene_expression)
#str(metadata)

# melting gene_expression data (using Tidyverse) from wide data to long data so the two files can be merged 
gene_long <- gene_expression %>%
  tidyr::gather(key = "ParticipantID", value = "Expression", -X)

# renaming the gene column to "Gene"
names(gene_long)[names(gene_long) == "X"] <- "Gene"

# checking the first 6 rows of the melted data
head(gene_long)

# merging the melted gene expression data with the metadata using the shared column of "ParticipantID"
merged_data <- merge(gene_long, metadata, by.x = "ParticipantID", by.y = "participant_id")
head(merged_data)

# filtered data using 'filter(Gene == A1CF) to only extract rows for where the gene is A1CF
# selecting columns for the covariate variables that I picked 
clean_data <- merged_data %>%
  filter(Gene == "ABCA1") %>%
  select(Gene, ParticipantID,Expression, age, sex, icu_status)

head(clean_data)

# checking data types of the columns
str(clean_data)

# converting age data to numeric - if not already
clean_data$age <- as.numeric(clean_data$age)

# converting sex and icu_status to factors - if not already
clean_data$sex <- as.factor(clean_data$sex)
clean_data$icu_status <- as.factor(clean_data$icu_status)

# confirming conversions 
str(clean_data)

# removing rows with missing values to 'final_data" which will be utilized for data visualization
final_data <- clean_data %>%
  filter(!is.na(sex) & sex != " unknown",
         !is.na(icu_status) & icu_status != " unknown")
```



```{r}
#Histogram for Gene Expression

library(ggplot2)

# initializes the plot with 'final_data' and maps all 'Expression' values to the x-axis
ggplot(final_data, aes(x = Expression)) + 
  geom_histogram(fill = "pink", color = "red") +
  # plots the histogram with bars outlined and filled
  labs(title = "Histogram of Gene Expression for ABCA1", # adds title and axis labels
       x = "Gene Expression: ABCA1",
       y = "Frequency") + 
  theme_minimal() + # applied minimal theme for appearance 
  theme( # making the titles of plot and axis bold
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.title = element_text(face = "bold"),
    legend.title = element_text(face = "bold")
  )

```



```{r}
# Scatterplot for gene expression and continuous covariate (Age)

library(ggplot2)

# initializes the plot with 'final_data' and maps all 'age' values to x-axis 'Expression' values to the y-axis
ggplot(final_data,aes(x = age,y = Expression ,color = age)) + 
  geom_point() + 
  scale_color_gradient(low = "green", high = "blue") + # color gradient for age 
  labs(title = "Scatterplot of Gene Expression for ABCA1 vs. Age (yrs.)", # title for plot and axis 
       subtitle = "Color indicates age, ranging from green (young) to blue (old)",
       x = "Age (yrs.)",
       y = "Gene Expression: ABCA1",
       color = "Age") + 
  theme_minimal() +
  theme( # making the titles of axis and plot bold 
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5), 
    axis.title = element_text(face = "bold"),
    legend.title = element_text(face = "bold")
  ) +

# adding a smooth line to show trend in data 
geom_smooth(method = "loess", se = FALSE, color = "black", linetype = "dashed")

```


```{r}
# Boxplot of gene expression separated by both categorical covariates (Sex and ICU Status)

library(ggplot2)
library(harrypotter)

# create boxplot with categorical covariates 
ggplot(final_data,aes(x = sex ,y = Expression, fill = icu_status)) +
   geom_boxplot(outlier.shape = 12, outlier.size = 2, color = "darkgray", lwd = 0.8, alpha = 0.7) + 
    scale_fill_hp_d(option = "ronweasley") + # change border color and box details 
  facet_wrap(~ icu_status) + # separate plots by ICU status
  labs(title = "Boxplot of Gene Expression by Sex and ICU Status", # assigned titles for axis and plot 
       x = "Sex",
       y = "Gene Expression",
       fill = "ICU Status") + 
  theme_minimal(base_size = 15) + # minimal theme with font size 
  theme( # making the titles of axis and plot bold, changing placement of titles 
    plot.title = element_text(hjust = 0.125, face = "bold"),
    axis.title = element_text(face = "bold"),
    legend.title = element_text(face = "bold")
  )

```


